config/routes.rb
DynamicRoles::Engine.routes.draw do
  resources :roles do
    resources :permissions, only: [:new, :create, :destroy]
  end
end

app/models/dynamic_roles/permission.rb
module DynamicRoles
  class Permission < ActiveRecord::Base
  end
end

app/models/dynamic_roles/role.rb
module DynamicRoles
  class Role < ActiveRecord::Base
    has_many :roles_permissions
    has_many :permissions, through: :roles_permissions
  end
end

app/models/dynamic_roles/roles_permission.rb
module DynamicRoles
  class RolesPermission < ActiveRecord::Base
    belongs_to :role
    belongs_to :permission

    validates :name, presence: true, length: {maximum: 100}
  end
end

app/models/dynamic_roles/user.rb
module DynamicRoles
  class User < ActiveRecord::Base
  end
end

app/models/dynamic_roles/users_role.rb
module DynamicRoles
  class UsersRole < ActiveRecord::Base
  end
end

app/controllers/dynamic_roles/application_controller.rb
module DynamicRoles
  class ApplicationController < ActionController::Base
  end
end

app/controllers/dynamic_roles/permissions_controller.rb
require_dependency "dynamic_roles/application_controller"

module DynamicRoles
  class PermissionsController < DynamicRoles::ApplicationController
    before_action :load_instance_role, only: [:new]

    def new

    end

    private
      def load_instance_role
        @role = DynamicRoles::Role.find_by!(id: params[:role_id])
      end
  end
end

app/controllers/dynamic_roles/roles_controller.rb
require_dependency "dynamic_roles/application_controller"

module DynamicRoles
  class RolesController < DynamicRoles::ApplicationController
    before_action :set_role, only: [:show, :edit, :update, :destroy]

    # GET /roles
    def index
      @roles = DynamicRoles::Role.all
    end

    # GET /roles/1
    def show
    end

    # GET /roles/new
    def new
      # fake data
      @permissions = Permission.all
      @role = DynamicRoles::Role.new
    end

    # GET /roles/1/edit
    def edit
    end

    # POST /roles
    def create
      @role = DynamicRoles::Role.new(role_params)

      if @role.save
        redirect_to @role, notice: 'Role was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /roles/1
    def update
      if @role.update(role_params)
        redirect_to @role, notice: 'Role was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /roles/1
    def destroy
      @role.destroy
      redirect_to roles_url, notice: 'Role was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_role
        @role = DynamicRoles::Role.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def role_params
        params.require(:role).permit(:name)
      end
  end
end

app/helpers/dynamic_roles/application_helper.rb
module DynamicRoles
  module ApplicationHelper
  end
end

app/helpers/dynamic_roles/permissions_helper.rb
module DynamicRoles
  module PermissionsHelper

    def default_controllers
      [DynamicRoles::PermissionsController, DynamicRoles::RolesController]
    end

    def permission_controllers
      default_controllers + option_controllers
    end

    def option_controllers
      Rails.application.config.dynamic_roles.permission_class
    end
  end
end

app/helpers/dynamic_roles/roles_helper.rb
module DynamicRoles
  module RolesHelper
  end
end

app/views/dynamic_roles/permissions/new.html.erb
<div class="row">
  <div class="col-xs-5">
    <select name="from[]" id="multiselect" class="form-control" size="8" multiple="multiple">
      <option value="1">Item 1</option>
      <option value="2">Item 5</option>
      <option value="2">Item 2</option>
      <option value="2">Item 4</option>
      <option value="3">Item 3</option>
    </select>
  </div>

  <div class="col-xs-2">
    <button type="button" id="multiselect_rightAll" class="btn btn-block">>></button>
    <button type="button" id="multiselect_rightSelected" class="btn btn-block">></button>
    <button type="button" id="multiselect_leftSelected" class="btn btn-block"><</button>
    <button type="button" id="multiselect_leftAll" class="btn btn-block"><</button>
  </div>

  <div class="col-xs-5">
    <select name="to[]" id="multiselect_to" class="form-control" size="8" multiple="multiple"></select>
  </div>
</div>

app/views/dynamic_roles/roles/_form.html.slim
= form_for(@role) do |f|
  - if @role.errors.any?
    #error_explanation
      h2 "#{pluralize(@role.errors.count, 'error')} prohibited this role from being saved:"
      ul
      - @role.errors.full_messages.each do |message|
        li = message
  .row
    .col-md-4.col-md-offset-2
      = f.label :name
      = f.text_field :name, class: "form-control"

      = label_tag :description
      = text_area_tag :description, "", class: "form-control"

      = f.submit "Submit", class: "btn-primary form-control"
      = link_to 'Back', roles_path

    .col-md-4
      = label_tag "Rule name"
      = select_tag "select rule", options_for_select(@permissions.collect{ |p| [p.name, p.id] }, ""), { class: "form-control" }

      = label_tag :data
      = text_area_tag :data, "", class: "form-control"

app/views/dynamic_roles/roles/edit.html.slim
.row
  .col-md-12.col-md-offset-2
    h2 Edit Role

= render 'form'

= link_to 'Show', @role
= link_to 'Back', roles_path

app/views/dynamic_roles/roles/index.html.slim
.row.col-md-8.col-md-offset-2
  h2 Roles
  = link_to 'New Role', new_role_path
  table.table.table-hover.table-bordered
    thead
      tr
        th #
        th Name roles
        th Description
        th
    tbody
      tr
        td
        td = text_field_tag :name_role, "", class: "form-control"
        td = text_field_tag :description_role, "", class: "form-control"
        td
      - @roles.each_with_index do |role, index|
        tr
          td = index.next
          td = role.name
          td
          td
            = link_to 'Show', role
            = link_to 'Edit', edit_role_path(role)
            = link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }

app/views/dynamic_roles/roles/new.html.slim
.row
  .col-md-12.col-md-offset-2
    h2 New Role

= render 'form'

app/views/dynamic_roles/roles/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>
<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>
<%= link_to 'Add permission', new_role_permission_path(@role) %>

app/views/dynamic_roles/roles/show.html.slim
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>
<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>
<%= link_to 'Add permission', new_role_permission_path(@role) %>

app/views/layouts/dynamic_roles/application.html.slim
doctype html
html lang="en"
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    title DynamicRoles
    = stylesheet_link_tag "dynamic_roles/application", media: 'all'
    = csrf_meta_tags
    = javascript_include_tag "dynamic_roles/application"
body
  nav.navbar.navbar-inverse
    .container-fluid
      .navbar-header
        a.navbar-brand
          | DynamicRoles
      ul.nav.navbar-nav
        li.active
          a[href="#"] Home
      ul.nav.navbar-nav.navbar-right
        li
          a[href="#"]
            span.glyphicon.glyphicon-user
            |  Sign Up
        li
          a[href="#"]
            span.glyphicon.glyphicon-log-in
            |  Login
  = yield